# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DMS for DSM V4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DMS for DSM V4
pod 'CryptoSwift'
pod 'RxAlamofire'
pod 'RxSwift'

end
